# This hook is activated when the GNOME night light is activated and runs until night light is deactivated again.

bus: session
actions:
  - device_id: 1
    zones: [0, 1, 2]
    colors:
      - [255, 255, 0]
  - device_id: 0
    zones: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    color: [255, 255, 0]
trigger:
  signal:
    path: /org/gnome/SettingsDaemon/Color
    interface: org.freedesktop.DBus.Properties
    name: PropertiesChanged
    eavesdrop: true
    arguments:
      - org.gnome.SettingsDaemon.Color
      - NightLightActive: true
until:
  signal:
    path: /org/gnome/SettingsDaemon/Color
    interface: org.freedesktop.DBus.Properties
    name: PropertiesChanged
    eavesdrop: true
    arguments:
      - org.gnome.SettingsDaemon.Color
      - NightLightActive: false
