bus: session
actions:
  - device_id: 1
    zones: [0, 1, 2]
    color: [0, 175, 240]
  - device_id: 0
    zones: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    color: [0, 175, 240]
trigger:
  signal:
    path: /org/gnome/SessionManager
    interface: org.gnome.SessionManager
    name: InhibitorAdded
    arguments: []
  conditions:
    - service_name: org.gnome.SessionManager
      path: ${sig_arg0}
      method: GetAppId
      response: "/usr/share/skypeforlinux/skypeforlinux"
    - service_name: org.gnome.SessionManager
      path: ${sig_arg0}
      method: GetReason
      response: "Playing audio"
until:
  signal:
    path: /org/gnome/SessionManager
    interface: org.gnome.SessionManager
    name: InhibitorRemoved
    arguments:
      - ${sig_arg0}
