# Turn lights WhatsApp-Green for one second when there's a notification coming from Web
# Whatsapp through Chromium.
# Sadly this method does not work on Firefox, since it does not share the source of the
# notification through the D-Bus.
# Chrome would probably also work, if `Chromium` was changed to `Chrome`.

bus: session
actions:
  - device_id: 1
    zones: [0, 1, 2]
    color: [37, 211, 102]
  - device_id: 0
    zones: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    color: [37, 211, 102]
trigger:
  signal:
    path: /org/freedesktop/Notifications
    interface: org.freedesktop.Notifications
    name: Notify
    eavesdrop: true
    # Chromium seems to maketwo Notify calls, but we only want to trigger once. Luckily only one of them is to org.freedesktop.Notifications
    destination: org.freedesktop.Notifications
    arguments:
      - Chromium
      -
      -
      -
      - web.whatsapp.com
until:
  sleep:
    duration: 1s
