# Example configuration that loads the hooks from different files.
# The !include statement places the parsed contents of the files as the direct value
# of the entry. If you do not like having multiple files, you can thus just paste
# the contents into the place of the !include statement

version: 0.4.0

logging: debug

server:
  port: 6742

hooks:
  # skype: !include hooks/skype.yaml
  # whatsapp: !include hooks/whatsapp.yaml
  # night_light: !include hooks/smooth_night_light.yaml
  # geary_mail: !include hooks/geary.yaml
  rainbow_notifications: !include hooks/rainbow_notifications.yaml
  # Disabled as it interferes any other notification based hook.
  # general_notifications: !include hooks/notifications.yaml
