version: 0.4.0

logging: debug

server:
  port: 6742

hooks:
  skype: !include hooks/skype.yaml
  whatsapp: !include hooks/whatsapp.yaml
  # Disabled as it interferes any other notification based hook.
  # general_notifications: !include hooks/notifications.yaml
